**Задание 1**  
Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

In [157]:
import pandas as pd

ratings = pd.read_csv('ml-latest-small/ratings.csv')
movies = pd.read_csv('ml-latest-small/movies.csv')

rating = 5.0
rated = ratings[ ratings['rating'] == rating ]
counts = rated['movieId'].value_counts()
if len(counts):
    mvid = counts.idxmax()
    name = movies[ movies['movieId'] == mvid ]['title']
    if len(name):
        print(f"Фильм \"{name.iloc[0]}\" набрал больше всего оценок {rating} ({counts.max()})")
    else:
        print(f"Фильм с ID = {mvid} набрал больше всего оценок {rating} ({counts.max()})")
else:
    print(f"Нет фильмов с оценкой {rating}")

Фильм "Shawshank Redemption, The (1994)" набрал больше всего оценок 5.0 (153)

**Задание 2**  
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.

In [158]:
power = pd.read_csv('power.csv')

power_balt = power[power['country'].isin(["Estonia", "Latvia", "Lithuania"]) &
                   power['category'].isin([4, 12, 21]) &
                   power['year'].isin([x for x in range(2005, 2011)])
                  ]['quantity'].sum()
print("Суммарное потребление:", power_balt)

Суммарное потребление: 240481.0

**Задание 3**  
Выберите страницу любого сайта с табличными данными. Импортируйте таблицы в pandas dataframe.
Примеры страниц (необязательно брать именно эти):  
https://fortrader.org/quotes  
https://www.finanz.ru/valyuty/v-realnom-vremeni

In [159]:
from IPython.display import display, HTML

def is_right_struct1(var):
    if len(var):
        for i in range(len(site1)):
            if (len(var[i].shape) != 2) or (var[i].shape[1] != 5):
                return False
        return True
    else:
        return False

def del_tooltip(var):
    '''Боремся с tooltip, попавшим в название'''
    lst = var.split(" ")
    if len(lst) == 1 or lst[1] in ["Акции", "Курс", "Цена", "Цены", "котировки", "Euro", "New", "US", "эфириум", lst[0]]:
        return lst[0]
    else:
        return lst[0] + " " + lst[1]
    
def parse_site1():
    try:
        site = pd.read_html("https://fortrader.org/quotes", converters={"Название": del_tooltip})
        if not is_right_struct1(site):
            raise;
    except:
        return
    
    for i in range(len(site)):
        site[i].drop("Обновлено", axis=1, inplace=True) # удаляем пустой столбец, т.к. парсер не осилил :(
        
    return pd.concat(site, ignore_index=True)

def is_right_struct2(var):
    return len(var) == 1 and (len(var[0].shape) == 2) and (var[0].shape == (3, 12))

def parse_site2():
    try:
        site = pd.read_html("https://www.finanz.ru/valyuty/v-realnom-vremeni", attrs={"class": "header_user_pricebox"}, encoding='utf-8')
        if not is_right_struct2(site):
            raise;
    except:
        return

    lst = []
    for i in range(0, 4):
        t = site[0][[x for x in range(i * 3, i * 3 + 3)]]
        t.columns = ['Название', 'Значение', 'Изменение']
        lst.append(t)
    
    return (site2[0], pd.concat(lst, ignore_index=True))


result1 = parse_site1()
if result1 is None:
    print("Парсер сайта fortrader.org не работает")
else:
    print("Объединенная таблица сайта fortrader.org (первые 10 значений)")
    display(HTML(result1.head(10).to_html()))
    
result2 = parse_site2()
if result2 is None:
    print("Парсер сайта finanz.ru не работает")
else:
    print("Таблица сайта finanz.ru (исходный вид)")
    display(HTML(result2[0].to_html()))
    print("Таблица сайта finanz.ru (вид для обработки)")
    display(HTML(result2[1].to_html()))

Объединенная таблица сайта fortrader.org (первые 10 значений)

Таблица сайта finanz.ru (исходный вид)

Таблица сайта finanz.ru (вид для обработки)